import { ApiError, api } from '@/lib/api/api-client';
import { logger } from '@/lib/logger';
import {
  ExpenseType,
  ExpenseCategory,
  ExpenseStatus,
  type Expense,
} from '@/types/finance/expense';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Raw = any;

function parseDate(val: unknown): Date {
  if (val instanceof Date) return val;
  if (typeof val === 'string' || typeof val === 'number') return new Date(val);
  return new Date();
}

function num(val: unknown): number {
  const n = Number(val);
  return Number.isFinite(n) ? n : 0;
}

function maybeNum(val: unknown): number | undefined {
  if (val == null || val === '') return undefined;
  const n = Number(val);
  return Number.isFinite(n) ? n : undefined;
}

/** Coerces a free-string column onto the enum, falling back when the stored value is unknown. */
function coerce<T extends Record<string, string>>(
  e: T,
  val: unknown,
  fallback: T[keyof T]
): T[keyof T] {
  const values = Object.values(e) as string[];
  return typeof val === 'string' && values.includes(val)
    ? (val as T[keyof T])
    : fallback;
}

/** Formats a date onto the `yyyy-MM-dd` the backend expects for `expenseDate`. */
function toDateString(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Derives a coarse payment status from the recorded lifecycle status. The backend
 * `ExpenseDto` does not track paid/balance amounts, so a paid or reimbursed expense
 * is treated as fully settled and everything else as unpaid.
 */
function derivePaymentStatus(status: ExpenseStatus): Expense['paymentStatus'] {
  if (status === ExpenseStatus.reimbursed) return 'reimbursed';
  if (status === ExpenseStatus.paid) return 'paid';
  return 'unpaid';
}

/**
 * Maps the backend `ExpenseDto` onto the richer web `Expense` model. The backend
 * returns a smaller field set (type, category, status, description, amount, currency,
 * expenseDate, paymentMethod, notes, the project/vendor/employee/invoice/payment/budget
 * links and audit fields), so the web-only fields default here: tax is not tracked
 * (total = amount), paid/balance are derived from the status, and the approval,
 * reimbursement, bill and attachment fields have no backend column yet.
 */
export function parseExpense(raw: Raw): Expense {
  if (raw?.id == null) {
    throw new Error('Invalid Expense data: missing id');
  }
  const amount = num(raw.amount);
  const status = coerce(ExpenseStatus, raw.status, ExpenseStatus.draft);
  const paymentStatus = derivePaymentStatus(status);
  const settled = paymentStatus === 'paid' || paymentStatus === 'reimbursed';
  const paidAmount = settled ? amount : 0;
  const employeeId = maybeNum(raw.employeeId);
  const createdAt = parseDate(raw.createdAt);

  return {
    id: raw.id,
    expenseNumber: raw.expenseNumber ?? String(raw.id),
    type: coerce(ExpenseType, raw.type, ExpenseType.direct),
    category: coerce(ExpenseCategory, raw.category, ExpenseCategory.other),
    status,

    projectId: maybeNum(raw.projectId),
    organizationId: maybeNum(raw.organizationId),
    vendorId: maybeNum(raw.vendorId),
    employeeId,
    invoiceId: maybeNum(raw.invoiceId),
    paymentId: maybeNum(raw.paymentId),
    budgetId: maybeNum(raw.budgetId),

    description: raw.description ?? '',
    amount,
    currency: raw.currency ?? 'INR',
    expenseDate: parseDate(raw.expenseDate),

    // Tax is not tracked by the backend, so the total is the bare amount.
    totalAmount: amount,

    paymentMethod: raw.paymentMethod ?? undefined,
    paymentStatus,
    paidAmount,
    balanceAmount: amount - paidAmount,

    // Approval workflow: only the incurring employee is known; submission is
    // stamped from the create timestamp, and there is no approval/rejection column.
    submittedBy: employeeId ?? 0,
    submittedAt: createdAt,

    notes: raw.notes ?? undefined,

    isReimbursable: false,

    createdBy: employeeId ?? 0,
    createdAt,
    updatedAt: parseDate(raw.updatedAt),
  };
}

function safeParse(raw: Raw): Expense {
  try {
    return parseExpense(raw);
  } catch (error) {
    logger.error('Failed to parse expense:', error);
    throw new ApiError('Failed to process expense data.', 422);
  }
}

const empty = (v?: string): string | undefined =>
  v && v.trim() !== '' ? v : undefined;

/**
 * Maps the expense form onto the backend `ExpenseCreationDto` / `ExpenseUpdateDto`.
 * Only the fields the backend accepts are sent; the expense number is generated by
 * the server, and the tax, payment-tracking, approval and reimbursement fields have
 * no backend column, so they are dropped from the payload.
 */
export function toPayload(data: Partial<Expense>): Record<string, unknown> {
  return {
    type: data.type,
    category: data.category,
    status: data.status,
    description: data.description,
    amount: data.amount,
    currency: data.currency,
    expenseDate: data.expenseDate ? toDateString(data.expenseDate) : undefined,
    paymentMethod: empty(data.paymentMethod),
    notes: empty(data.notes),
    projectId: data.projectId,
    vendorId: data.vendorId,
    employeeId: data.employeeId,
    invoiceId: data.invoiceId,
    paymentId: data.paymentId,
    budgetId: data.budgetId,
  };
}

const BASE = '/expenses/web';

/** Backend-backed expenses (`/api/v1/expenses/web`). */
export const expensesService = {
  async getAll(): Promise<Expense[]> {
    const data = await api.get<Raw>(BASE);
    const rows: Raw[] = Array.isArray(data) ? data : (data?.content ?? []);
    return rows.map((row) => safeParse(row));
  },

  async getById(id: number): Promise<Expense> {
    const raw = await api.get<Raw>(`${BASE}/${id}`);
    return safeParse(raw);
  },

  async create(data: Partial<Expense>): Promise<Expense> {
    const raw = await api.post<Raw>(BASE, toPayload(data));
    return safeParse(raw);
  },

  async update(id: number, data: Partial<Expense>): Promise<Expense> {
    const raw = await api.put<Raw>(`${BASE}/${id}`, toPayload(data));
    return safeParse(raw);
  },

  async remove(id: number): Promise<void> {
    await api.delete(`${BASE}/${id}`);
  },
};
