import { ApiError, api } from '@/lib/api/api-client';
import { logger } from '@/lib/logger';
import { ReceiptType, ReceiptStatus, type Receipt } from '@/types/finance/receipt';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Raw = any;

function parseDate(val: unknown): Date {
  if (val instanceof Date) return val;
  if (typeof val === 'string' || typeof val === 'number') return new Date(val);
  return new Date();
}

/** Renders a raw backend value into the ISO date string the web Receipt model holds. */
function toIsoString(val: unknown): string {
  if (val instanceof Date) return val.toISOString();
  if (typeof val === 'string' || typeof val === 'number') {
    const d = new Date(val);
    if (!Number.isNaN(d.getTime())) return d.toISOString();
  }
  return new Date().toISOString();
}

function num(val: unknown): number {
  const n = Number(val);
  return Number.isFinite(n) ? n : 0;
}

function maybeNum(val: unknown): number | undefined {
  if (val == null || val === '') return undefined;
  const n = Number(val);
  return Number.isFinite(n) ? n : undefined;
}

/** Coerces a free-string column onto the enum, falling back when the stored value is unknown. */
function coerce<T extends Record<string, string>>(
  e: T,
  val: unknown,
  fallback: T[keyof T]
): T[keyof T] {
  const values = Object.values(e) as string[];
  return typeof val === 'string' && values.includes(val)
    ? (val as T[keyof T])
    : fallback;
}

/** Formats a date onto the `yyyy-MM-dd` the backend expects for `receiptDate`. */
function toDateString(value: unknown): string | undefined {
  if (value == null || value === '') return undefined;
  const date = value instanceof Date ? value : new Date(value as string);
  if (Number.isNaN(date.getTime())) return undefined;
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Maps the backend `ReceiptDto` onto the web `Receipt` model. The backend returns
 * the receipt number, type, status, amount, currency, receiptDate, paymentMethod,
 * transaction/reference details, payer, tax fields, description, notes, the
 * project/payment/invoice/customer/organization links, issuedBy and the audit
 * timestamps. The web-only fields default here: there is no separate `issuedAt`
 * column, so it mirrors the create timestamp; `createdBy` falls back to the issuer;
 * and `attachments` has no backend column yet, so it is left unset.
 */
export function parseReceipt(raw: Raw): Receipt {
  if (raw?.id == null) {
    throw new Error('Invalid Receipt data: missing id');
  }
  const issuedBy = num(raw.issuedBy);
  const createdAt = parseDate(raw.createdAt);

  return {
    id: raw.id,
    receiptNumber: raw.receiptNumber ?? String(raw.id),
    type: coerce(ReceiptType, raw.type, ReceiptType.payment),
    status: coerce(ReceiptStatus, raw.status, ReceiptStatus.draft),

    projectId: num(raw.projectId),
    paymentId: maybeNum(raw.paymentId),
    invoiceId: maybeNum(raw.invoiceId),
    organizationId: maybeNum(raw.organizationId),
    customerId: maybeNum(raw.customerId),

    amount: num(raw.amount),
    currency: raw.currency ?? 'INR',
    receiptDate: toIsoString(raw.receiptDate),
    paymentMethod: raw.paymentMethod ?? '',

    transactionId: raw.transactionId ?? undefined,
    referenceNumber: raw.referenceNumber ?? undefined,

    receivedFrom: raw.receivedFrom ?? '',
    receivedFromAddress: raw.receivedFromAddress ?? undefined,

    taxAmount: maybeNum(raw.taxAmount),
    taxRate: maybeNum(raw.taxRate),
    taxType: raw.taxType ?? undefined,

    description: raw.description ?? undefined,
    notes: raw.notes ?? undefined,

    // No backend column yet, so attachments stay unset.

    issuedBy,
    // The backend does not track a separate issued timestamp; mirror the create time.
    issuedAt: createdAt,

    createdBy: maybeNum(raw.createdBy) ?? issuedBy,
    createdAt,
    updatedAt: parseDate(raw.updatedAt ?? raw.createdAt),
  };
}

function safeParse(raw: Raw): Receipt {
  try {
    return parseReceipt(raw);
  } catch (error) {
    logger.error('Failed to parse receipt:', error);
    throw new ApiError('Failed to process receipt data.', 422);
  }
}

const empty = (v?: string): string | undefined =>
  v && v.trim() !== '' ? v : undefined;

/**
 * Maps the receipt form onto the backend `ReceiptCreationDto` / `ReceiptUpdateDto`.
 * Only the fields the backend accepts are sent; the receipt number is generated by
 * the server, and the attachment data has no backend column, so it is dropped from
 * the payload.
 */
export function toPayload(data: Partial<Receipt>): Record<string, unknown> {
  return {
    type: data.type,
    status: data.status,
    amount: data.amount,
    currency: data.currency,
    receiptDate: toDateString(data.receiptDate),
    paymentMethod: empty(data.paymentMethod),
    transactionId: empty(data.transactionId),
    referenceNumber: empty(data.referenceNumber),
    receivedFrom: data.receivedFrom,
    receivedFromAddress: empty(data.receivedFromAddress),
    taxAmount: data.taxAmount,
    taxRate: data.taxRate,
    taxType: empty(data.taxType),
    description: empty(data.description),
    notes: empty(data.notes),
    issuedBy: data.issuedBy,
    projectId: data.projectId,
    paymentId: data.paymentId,
    invoiceId: data.invoiceId,
    customerId: data.customerId,
  };
}

const BASE = '/receipts/web';

/** Backend-backed receipts (`/api/v1/receipts/web`). */
export const receiptsService = {
  async getAll(): Promise<Receipt[]> {
    const data = await api.get<Raw>(BASE);
    const rows: Raw[] = Array.isArray(data) ? data : (data?.content ?? []);
    return rows.map((row) => safeParse(row));
  },

  async getById(id: number): Promise<Receipt> {
    const raw = await api.get<Raw>(`${BASE}/${id}`);
    return safeParse(raw);
  },

  async create(data: Partial<Receipt>): Promise<Receipt> {
    const raw = await api.post<Raw>(BASE, toPayload(data));
    return safeParse(raw);
  },

  async update(id: number, data: Partial<Receipt>): Promise<Receipt> {
    const raw = await api.put<Raw>(`${BASE}/${id}`, toPayload(data));
    return safeParse(raw);
  },

  async remove(id: number): Promise<void> {
    await api.delete(`${BASE}/${id}`);
  },
};
